name: Docker Image CI FAST API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: SonarCloud Scan
      working-directory: v1/
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Build and push Docker images
      working-directory: v1/
      run: |
        docker buildx create --use
        docker buildx build \
          --file Dockerfile \
          --tag 1bira/fastapi-simple-app:latest \
          --push .
          
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        # The path to the Dockerfile to lint
        dockerfile: Dockerfile
        
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
    
