on:
  push:
    branches: [ main ]
    # paths: ["v1/manifests/**"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4     
      - name: GitHub Push        
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PUSH_TOKEN}}
          repository: "https://github.com/1Bira/gitops-repo-poc-v1.git" # optional, default is 
          # Destination branch to push changes
          branch: main # optional, default is master
          # Determines if force push is used
          force: yes # optional
          # Determines if --tags is used
          
