on:
  push:
    branches: [ main ]
    paths: ["v1/manifests/**"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4     
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}
        with:
          source-directory: 'v1/manifests/'
          destination-github-username: '1bira'
          destination-repository-name: 'gitops-repo-poc-v1'
          user-email: ${{secrets.PUSH_TOKEN}}
          target-branch: main
          target-directory: 'cluster/dev/'
          
