on:
  push:
    branches: [ main ]
    paths: ["v1/manifests/**"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup git config
        run: | 
          git config --local user.name 1bira
          git config --local user.email ${{secrets.EMAIL}}
          git add ./v1/manifests/
          git commit -m "Update manifests"
          git push https://$USERNAME:$REPO_KEY@github.com/1bira/gitops-repo-poc-v1.git
        env:
          REPO_KEY: ${{secrets.PUSH_TOKEN}}
          USERNAME: 1bira
          
