on:
  push:
    branches: [ main ]
    # paths: ["v1/manifests/**"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4     
      - name: setup git config
        run: | 
          cd v1/manifests
          git config --local user.name $USERNAME
          git config --local user.email ${{secrets.EMAIL}}
          echo "Working Directory: $(pwd)"

          # Print values.yaml for debugging before changes
          echo "Before modification:"
          cat service.yaml
          
          git remote set-url origin https://github.com/1Bira/gitops-repo-poc-v1.git
          echo "add remote origin $(git remote show origin)"
          git branch -M main
          echo "Commit"
          git add service.yaml
          git commit -m "Update manifests"
          git push https://$USERNAME:$REPO_KEY@github.com/1bira/gitops-repo-poc-v1.git
        env:
          REPO_KEY: ${{secrets.PUSH_TOKEN}}
          USERNAME: 1bira
          
